### ISSUE TITLE
Error on a non test star

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#10]
Tried on first star listed in SWEET-Cat "11 Com", got the following error:

Not sure if is related with the space in the name, or the download of a single spectrum for one instrument...

```
Download completed successfully.
Making the final data frame...
File not found: pipeline_products/11 Com/11 Com_HARPS/df_stats_11 Com.fits
File not found: pipeline_products/11 Com/11 Com_ESPRESSO/df_stats_11 Com.fits
File not found: pipeline_products/11 Com/11 Com_UVES/df_stats_11 Com.fits
Traceback (most recent call last):
  File "/home/sousasag/anaconda3/envs/saitama/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'instr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 38, in <module>
    SAITAMA(stars, instruments, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 412, in SAITAMA
    plot_RV_indices_diff_instr(star_name,master_df,indices,save=True,path_save= f"{final_path}/{star_name}/{star_name}.pdf")
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/pipeline_functions/general_funcs.py", line 333, in plot_RV_indices_diff_instr
    instruments = df["instr"].unique()  # Get unique instruments
                  ~~^^^^^^^^^
  File "/home/sousasag/anaconda3/envs/saitama/lib/python3.11/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sousasag/anaconda3/envs/saitama/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'instr'
```

**Comment by sousasag** [comment]
The problem was the space. in "11 Com", changing to "11Com" avoided the crash.
