### ISSUE TITLE
Error on specific target

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#11]
Testing for "TOI-908" got the following error:

```
Download completed successfully.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [01:16<00:00,  1.63s/it]
Processing the data...
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 35, in <module>
    SAITAMA(stars, instruments, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 316, in SAITAMA
    df = df.drop(labels=list(bad_spec_indices)) #dropping the badly corrected spectra
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sousasag/Programas/anaconda3/envs/saitama/lib/python3.11/site-packages/pandas/core/frame.py", line 5581, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/sousasag/Programas/anaconda3/envs/saitama/lib/python3.11/site-packages/pandas/core/generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sousasag/Programas/anaconda3/envs/saitama/lib/python3.11/site-packages/pandas/core/generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sousasag/Programas/anaconda3/envs/saitama/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: '[0] not found in axis'
```

**Comment by telmonteiro** [comment]
Changed
`df = df.drop(labels=list(bad_spec_indices))`

to

`df = df.drop(list(bad_spec_indices)).reset_index(drop=True)`
