### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#2]
Error on plotting errors with matplotlib, but the error might come from pandas. Could it be a problem with version of pandas?

I am using :pd.__version__ '1.5.3'

Here is the error that I got in two places of the code:

```
python ACTINometer.py 
INFO: Authenticating sousasag on www.eso.org... [astroquery.eso.core]
INFO: Authentication successful! [astroquery.eso.core]
HD47536 GAIA DR3 5583831735369515008
Processing spectra from HARPS instrument...
Processing spectra from ESPRESSO instrument...
Processing spectra from UVES instrument...
  0%|                                                                                                                                           | 0/6 [00:00<?, ?it/s]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 17%|█████████████████████▊                                                                                                             | 1/6 [00:03<00:15,  3.01s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 33%|███████████████████████████████████████████▋                                                                                       | 2/6 [00:05<00:11,  2.89s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 50%|█████████████████████████████████████████████████████████████████▌                                                                 | 3/6 [00:08<00:08,  2.91s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 67%|███████████████████████████████████████████████████████████████████████████████████████▎                                           | 4/6 [00:11<00:05,  2.90s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 5/6 [00:14<00:02,  2.91s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:17<00:00,  2.90s/it]
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py", line 528, in <module>
    main(stars, instruments, columns_df, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py", line 500, in main
    pipeline(stars, instruments, columns_df, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py", line 325, in pipeline
    plot_RV_indices(target_save_name,df,indices,save=True,path_save=folder_path + f"{target_save_name}_{instr}.pdf")
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/general_funcs.py", line 150, in plot_RV_indices
    plt.errorbar(df.bjd - 2450000, df[index], df[index + "_err"], fmt='k.')
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2564, in errorbar
    return gca().errorbar(
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 3534, in errorbar
    yerr = _upcast_err(yerr)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 3516, in _upcast_err
    isinstance(cbook._safe_first_finite(err), np.ndarray)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1715, in _safe_first_finite
    return next(val for val in obj if safe_isfinite(val))
StopIteration
```

```
python ACTINometer.py 
INFO: Authenticating sousasag on www.eso.org... [astroquery.eso.core]
INFO: Authentication successful! [astroquery.eso.core]
HD47536 GAIA DR3 5583831735369515008
Processing spectra from HARPS instrument...
Processing spectra from ESPRESSO instrument...
Processing spectra from UVES instrument...
  0%|                                                                                                                                           | 0/6 [00:00<?, ?it/s]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 17%|█████████████████████▊                                                                                                             | 1/6 [00:03<00:15,  3.03s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 33%|███████████████████████████████████████████▋                                                                                       | 2/6 [00:05<00:11,  2.86s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 50%|█████████████████████████████████████████████████████████████████▌                                                                 | 3/6 [00:08<00:08,  2.91s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 67%|███████████████████████████████████████████████████████████████████████████████████████▎                                           | 4/6 [00:11<00:05,  2.90s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 5/6 [00:14<00:02,  2.96s/it]/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py:284: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame([{**df_ind, **headers}]),ignore_index=True,sort=True)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:17<00:00,  2.93s/it]
File not found: teste_download_rv_corr/HD47536/HD47536_HARPS/df_stats_HD47536.fits
File not found: teste_download_rv_corr/HD47536/HD47536_ESPRESSO/df_stats_HD47536.fits
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py", line 528, in <module>
    main(stars, instruments, columns_df, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py", line 500, in main
    pipeline(stars, instruments, columns_df, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/ACTINometer.py", line 424, in pipeline
    plot_RV_indices_diff_instr(target_save_name,master_df,indices,save=True,path_save= f"{final_path}/{target_save_name}/{target_save_name}.pdf")
  File "/home/sousasag/Programas/GIT_projects/Others/PEEC-24/general_funcs.py", line 333, in plot_RV_indices_diff_instr
    plt.errorbar(instr_df["bjd"] - 2450000, instr_df[index], instr_df[index + "_err"], fmt='.', label=instrument)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2564, in errorbar
    return gca().errorbar(
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/__init__.py", line 1442, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 3534, in errorbar
    yerr = _upcast_err(yerr)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 3516, in _upcast_err
    isinstance(cbook._safe_first_finite(err), np.ndarray)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1715, in _safe_first_finite
    return next(val for val in obj if safe_isfinite(val))
StopIteration

```

**Comment by telmonteiro** [comment]
I was using an old version for both Python and for packages such as matplotlib and pandas. I updated the packages and now I'm also using pandas :pd.version '1.5.3', in Python 3.10.12. I tested the pipeline and for me there is no errors. 

Please try to run the code again (READme was also updated) and let me know if the error persists!
