### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#5]
I get the error:

```
Traceback (most recent call last):
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 35, in <module>
    SAITAMA(stars, instruments, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 336, in SAITAMA
    if n_spec >= 50 and t_span >= 2 * 365 and math.isnan(I_CaII[0]) == False:
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 981, in __getitem__
    return self._get_value(key)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "/home/sousasag/Programas/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 0
```
`math.isnan(I_CaII.iloc[0]) == False`

What is the goal with this line?:

https://github.com/telmonteiro/SAITAMA/blob/d6c4f5f35c7d7ac5f4c58e372d9c8c9b2b3a8937/SAITAMA.py#L333

Specially the

`math.isnan(I_CaII[0]) == False`

In my computer I get a data frame but the index is not zero:

```
print(I_CaII)

3      0.158866
6      0.157728
8      0.152363
9      0.156847
10     0.132404
         ...   
142    0.136884
143    0.135427
144    0.154160
145    0.158545
146    0.149617
Name: I_CaII, Length: 94, dtype: float64

```

A quick fix was to do:

`math.isnan(I_CaII.iloc[0]) == False`

**Comment by telmonteiro** [comment]
The goal of the line
` if n_spec >= 50 and t_span >= 2 * 365 and math.isnan(I_CaII[0]) == False: `
is to make sure that the data frame includes at least 50 spectra spreading in a time span of 2 years. The last part acts as a safeguard in the case that the star does not have spectra in the ESO data base from the required spectrograph, which may return a column with NaN values.

Nonetheless, the quality cuts in the pipeline mess with the indices of the columns, so the suggested fix
`math.isnan(I_CaII.iloc[0]) == False`
is much better. Thank you!
