### ISSUE TITLE
got multiple values for argument 'y_err'

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#6]
```
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 35, in <module>
    SAITAMA(stars, instruments, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 343, in SAITAMA
    results, gaps, flag_period, period, period_err, harmonics_list, amplitude, amplitude_err = gls(star_name, instr, df, bjd-2450000, I_CaII, y_err=I_CaII_err, 
TypeError: gls() got multiple values for argument 'y_err'
```

```
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 35, in <module>
    SAITAMA(stars, instruments, indices, max_spectra, min_snr, download, neglect_data, username_eso, download_path, final_path)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 425, in SAITAMA
    results, gaps, flag_period, period, period_err, harmonics_list, amplitude, amplitude_err = gls(star_name, None, master_df, bjd-2450000, I_CaII, y_err=I_CaII_err, 
TypeError: gls() got multiple values for argument 'y_err'

```

I removed the df, and the master_df, which seems to be in excess in the function call.

**Comment by telmonteiro** [comment]
Indeed the arguments were in excess. Thank you!
